Added enum and oneof streaming tests
ni/grpc-labview pull request #306
Opened 2023-09-11 06:05 UTC by yash-ni

* Added enum and oneof streaming tests
* Added Generated_server folders for each test
* Added new variable "clean_gen" in testlist.json to enable regeneration (Generating server without deleting the pre-existing server)

2023-09-12 06:38 UTC, ni-sujain commented on tests/New_ATS/Tests/oneof-streaming/Python_client/ServerStreamingMethod_client.py
> +
add a comment that the test case json for this only has message as input for oneof message

2023-09-12 06:41 UTC, ni-sujain commented on tests/New_ATS/Tests/oneof-streaming/oneof-streaming.proto
> +  // operation - increments and request_id by 1, appends _response to message
copy these comments for RPC method to .py client files

2023-09-12 06:43 UTC, ni-sujain commented on tests/New_ATS/pylib/run_tests.py
> +                test_config['python_server_folder'] = test_config['test_folder'] / 'Python_server'
add a readme for purpose of Python_server folder.

2023-09-12 06:44 UTC, ni-sujain commented on tests/New_ATS/pylib/testlist.json
> +    "clean_gen": true
Update the read me to include this flag, mention that its always clean gen by default

2023-09-12 07:01 UTC, ni-sujain requested changes
We dont have to add the generated_server folder . We can run the codegen twice. Modify the run_test.py to accommodate this

2023-09-12 07:05 UTC, ni-sujain commented on tests/New_ATS/.gitignore
Since we are not submitting the generated_server folder we have to ignore that while running the test

2023-09-13 05:15 UTC, ni-sujain commented on tests/New_ATS/Tests/oneof-streaming/oneof-streaming.proto
> +  // operation - increments and request_id by 1, appends _response to message
I dont see the comments yet in the python clients

2023-09-13 05:16 UTC, ni-sujain approved these changes
update comments and update readme

2023-09-13 10:15 UTC, yash-ni commented
> update comments and update readme

Added comments in python clients, python servers and protofiles for all the tests

2023-09-13 17:20 UTC, merged